using UnityEngine;
using System.Collections;

[RequireComponent(typeof(AudioSource))]
public class AudioManager : MonoBehaviour {

	public AudioSource musicSource;
	private AudioClip mainMusic;

	private static AudioManager _instance;
	public static AudioManager instance
	{
		get
		{
			if (_instance == null)
			{
				_instance = FindObjectOfType<AudioManager>();
			}
			if (_instance == null)
			{
				GameObject go = new GameObject("AudioManager_autogenerated");
				_instance = go.AddComponent<AudioManager>();
			}
            return _instance;
        }
    }
	
	private AudioSource _source;
	private AudioSource _VOSource;
	
	public AudioSource source
	{
		get
		{
			if (_source == null)
			{
				_source = GetComponent<AudioSource>();
			}
			return _source;
		}
	}
	
	public AudioSource VOSource
	{
		get
		{
			if(_VOSource == null)
			{
				foreach(Transform tr in this.transform)
					if(tr.name == "Voiceovers")
						_VOSource = tr.GetComponent<AudioSource>();
			}
			return _VOSource;
		}
	}
		
	void Awake()
	{
		if (musicSource != null)
			mainMusic = musicSource.clip;
	}
	
	public void PlaySound(AudioClip clip)
	{
		source.clip = clip;
		source.PlayControlled(AudioType.Sound);
	}
	
	public void PlayVO(AudioClip clip)
	{
		VOSource.clip = clip;
		VOSource.PlayControlled(AudioType.VoiceOver);
	}

//	public void SwitchMusic(AudioClip music)
//	{
//		StartCoroutine(SwitchMusicCoroutine(music));
//	}
//
//	public void SwitchToMainMusic()
//	{
//		StartCoroutine(SwitchMusicCoroutine(mainMusic));
//	}

//	IEnumerator SwitchMusicCoroutine(AudioClip music)
//	{
//		musicSource.GetOrAddComponent<VolumeTweenable>().Tween(0.1f, 0.5f);
//		yield return new WaitForSeconds(0.5f);
//		musicSource.clip = music;
//		musicSource.Play();
//		musicSource.GetOrAddComponent<VolumeTweenable>().Tween(1f, 0.5f);
//	}
}
